#ifndef SHARED_H
#define SHARED_H

#define POWERSETTING 3

enum {
  AM_BLINKTORADIO = 9,
  PACKET_SIZE = 128,
  AM_NODEA=1,
  AM_NODEB=2,
  AM_NODEC=3,
  TIMER_PERIOD_MILLI = 200,
  BETWEEN_REQUEST_PERIOD_MILLI = 3000,
  REQUEST_PERIOD_MILLI = 800,
  TEMP_PERIOD_MILLI = 500,
  FIGHT_PERIOD_MILLI = 1000
};

#endif /* SHARED_H */
